### ISSUE TITLE
Github Login

### ISSUE THREAD

**Issue by Twipped** [Basedash/dockhunt#25] opened 2023-02-07 18:59 UTC
**Is your feature request related to a problem? Please describe.**

With Twitter ending API access soon, and the future of the platform being uncertain at best, perhaps this should support login from other platforms? Github seems obvious, but email auth would be ideal.

**Describe the solution you'd like**

More options for account authentication than just twitter.

**Describe alternatives you've considered**

There doesn't appear to be any alternative option.

**Comment by 5ouma** [comment] 2023-06-10 00:46
I’m not sure whether they’ll implement this feature because of this issue https://github.com/Basedash/dockhunt/issues/11.

**Comment by MaxMusing** [comment] 2023-08-25 02:04
Duplicate of #11. Open to PRs if anyone wants to take a crack at adding support for alternative auth providers.

**Closed by MaxMusing** 2023-08-25 02:04 UTC
Labels: enhancement
